// Seed data for Province/State and Highways
export const PROVINCES = [
  { country: 'CA', code: 'ON', label: 'Ontario' },
  { country: 'CA', code: 'QC', label: 'Quebec' },
  // US states (just MI for seed, rest lazy-load)
  { country: 'US', code: 'MI', label: 'Michigan' },
  { country: 'US', code: 'AL', label: 'Alabama' },
  { country: 'US', code: 'AK', label: 'Alaska' },
  { country: 'US', code: 'AZ', label: 'Arizona' },
  { country: 'US', code: 'AR', label: 'Arkansas' },
  { country: 'US', code: 'CA', label: 'California' },
  { country: 'US', code: 'CO', label: 'Colorado' },
  { country: 'US', code: 'CT', label: 'Connecticut' },
  { country: 'US', code: 'DE', label: 'Delaware' },
  { country: 'US', code: 'FL', label: 'Florida' },
  { country: 'US', code: 'GA', label: 'Georgia' },
  { country: 'US', code: 'HI', label: 'Hawaii' },
  { country: 'US', code: 'ID', label: 'Idaho' },
  { country: 'US', code: 'IL', label: 'Illinois' },
  { country: 'US', code: 'IN', label: 'Indiana' },
  { country: 'US', code: 'IA', label: 'Iowa' },
  { country: 'US', code: 'KS', label: 'Kansas' },
  { country: 'US', code: 'KY', label: 'Kentucky' },
  { country: 'US', code: 'LA', label: 'Louisiana' },
  { country: 'US', code: 'ME', label: 'Maine' },
  { country: 'US', code: 'MD', label: 'Maryland' },
  { country: 'US', code: 'MA', label: 'Massachusetts' },
  { country: 'US', code: 'MN', label: 'Minnesota' },
  { country: 'US', code: 'MS', label: 'Mississippi' },
  { country: 'US', code: 'MO', label: 'Missouri' },
  { country: 'US', code: 'MT', label: 'Montana' },
  { country: 'US', code: 'NE', label: 'Nebraska' },
  { country: 'US', code: 'NV', label: 'Nevada' },
  { country: 'US', code: 'NH', label: 'New Hampshire' },
  { country: 'US', code: 'NJ', label: 'New Jersey' },
  { country: 'US', code: 'NM', label: 'New Mexico' },
  { country: 'US', code: 'NY', label: 'New York' },
  { country: 'US', code: 'NC', label: 'North Carolina' },
  { country: 'US', code: 'ND', label: 'North Dakota' },
  { country: 'US', code: 'OH', label: 'Ohio' },
  { country: 'US', code: 'OK', label: 'Oklahoma' },
  { country: 'US', code: 'OR', label: 'Oregon' },
  { country: 'US', code: 'PA', label: 'Pennsylvania' },
  { country: 'US', code: 'RI', label: 'Rhode Island' },
  { country: 'US', code: 'SC', label: 'South Carolina' },
  { country: 'US', code: 'SD', label: 'South Dakota' },
  { country: 'US', code: 'TN', label: 'Tennessee' },
  { country: 'US', code: 'TX', label: 'Texas' },
  { country: 'US', code: 'UT', label: 'Utah' },
  { country: 'US', code: 'VT', label: 'Vermont' },
  { country: 'US', code: 'VA', label: 'Virginia' },
  { country: 'US', code: 'WA', label: 'Washington' },
  { country: 'US', code: 'WV', label: 'West Virginia' },
  { country: 'US', code: 'WI', label: 'Wisconsin' },
  { country: 'US', code: 'WY', label: 'Wyoming' },
  { country: 'US', code: 'DC', label: 'District of Columbia' }
];

export const HIGHWAYS = {
  'CA-ON': [
    { code: '401', type: 'Hwy', label: 'Hwy 401', synonyms: ['401', 'Highway 401'] },
    { code: '402', type: 'Hwy', label: 'Hwy 402', synonyms: ['402'] },
    { code: '403', type: 'Hwy', label: 'Hwy 403', synonyms: ['403'] },
    { code: '404', type: 'Hwy', label: 'Hwy 404', synonyms: ['404'] },
    { code: '405', type: 'Hwy', label: 'Hwy 405', synonyms: ['405'] },
    { code: '406', type: 'Hwy', label: 'Hwy 406', synonyms: ['406'] },
    { code: '407', type: 'Hwy', label: 'Hwy 407 (Toll)', synonyms: ['407', '407 ETR', '407 toll'] },
    { code: '409', type: 'Hwy', label: 'Hwy 409', synonyms: ['409'] },
    { code: '410', type: 'Hwy', label: 'Hwy 410', synonyms: ['410'] },
    { code: '412', type: 'Hwy', label: 'Hwy 412 (Toll)', synonyms: ['412', '412 toll'] },
    { code: '416', type: 'Hwy', label: 'Hwy 416', synonyms: ['416'] },
    { code: '417', type: 'Hwy', label: 'Hwy 417', synonyms: ['417'] },
    { code: '418', type: 'Hwy', label: 'Hwy 418 (Toll)', synonyms: ['418', '418 toll'] },
    { code: '420', type: 'Hwy', label: 'Hwy 420', synonyms: ['420'] },
    { code: '427', type: 'Hwy', label: 'Hwy 427', synonyms: ['427'] },
    { code: 'QEW', type: 'Hwy', label: 'QEW', synonyms: ['QEW', 'Queen Elizabeth Way'] },
    { code: '2', type: 'Hwy', label: 'Hwy 2', synonyms: ['2'] },
    { code: '3', type: 'Hwy', label: 'Hwy 3', synonyms: ['3'] },
    { code: '6', type: 'Hwy', label: 'Hwy 6', synonyms: ['6'] },
    { code: '7', type: 'Hwy', label: 'Hwy 7', synonyms: ['7'] },
    { code: '8', type: 'Hwy', label: 'Hwy 8', synonyms: ['8'] },
    { code: '9', type: 'Hwy', label: 'Hwy 9', synonyms: ['9'] },
    { code: '11', type: 'Hwy', label: 'Hwy 11', synonyms: ['11'] },
    { code: '12', type: 'Hwy', label: 'Hwy 12', synonyms: ['12'] },
    { code: '17', type: 'Hwy', label: 'Hwy 17', synonyms: ['17'] },
    { code: '28', type: 'Hwy', label: 'Hwy 28', synonyms: ['28'] },
    { code: '35/115', type: 'Hwy', label: 'Hwy 35/115', synonyms: ['35/115'] },
    { code: '37', type: 'Hwy', label: 'Hwy 37', synonyms: ['37'] },
    { code: '60', type: 'Hwy', label: 'Hwy 60', synonyms: ['60'] },
    { code: '62', type: 'Hwy', label: 'Hwy 62', synonyms: ['62'] },
    { code: '69', type: 'Hwy', label: 'Hwy 69', synonyms: ['69'] },
    { code: '118', type: 'Hwy', label: 'Hwy 118', synonyms: ['118'] },
    { code: '124', type: 'Hwy', label: 'Hwy 124', synonyms: ['124'] },
    { code: '144', type: 'Hwy', label: 'Hwy 144', synonyms: ['144'] },
    { code: '174', type: 'Hwy', label: 'Hwy 174', synonyms: ['174'] }
  ],
  'CA-QC': [
    { code: 'A-10', type: 'Autoroute', label: 'Autoroute 10', synonyms: ['A-10', 'Autoroute 10'] },
    { code: 'A-13', type: 'Autoroute', label: 'Autoroute 13', synonyms: ['A-13', 'Autoroute 13'] },
    { code: 'A-15', type: 'Autoroute', label: 'Autoroute 15', synonyms: ['A-15', 'Autoroute 15'] },
    { code: 'A-19', type: 'Autoroute', label: 'Autoroute 19', synonyms: ['A-19', 'Autoroute 19'] },
    { code: 'A-20', type: 'Autoroute', label: 'Autoroute 20', synonyms: ['A-20', 'Autoroute 20', '20'] },
    { code: 'A-25', type: 'Autoroute', label: 'Autoroute 25', synonyms: ['A-25', 'Autoroute 25'] },
    { code: 'A-30', type: 'Autoroute', label: 'Autoroute 30', synonyms: ['A-30', 'Autoroute 30'] },
    { code: 'A-35', type: 'Autoroute', label: 'Autoroute 35', synonyms: ['A-35', 'Autoroute 35'] },
    { code: 'A-40', type: 'Autoroute', label: 'Autoroute 40', synonyms: ['A-40', 'Autoroute 40', '40'] },
    { code: 'A-50', type: 'Autoroute', label: 'Autoroute 50', synonyms: ['A-50', 'Autoroute 50'] },
    { code: 'A-55', type: 'Autoroute', label: 'Autoroute 55', synonyms: ['A-55', 'Autoroute 55'] },
    { code: 'A-73', type: 'Autoroute', label: 'Autoroute 73', synonyms: ['A-73', 'Autoroute 73'] },
    { code: 'A-85', type: 'Autoroute', label: 'Autoroute 85', synonyms: ['A-85', 'Autoroute 85'] },
    { code: '132', type: 'Route', label: 'Route 132', synonyms: ['132', 'Route 132'] },
    { code: '138', type: 'Route', label: 'Route 138', synonyms: ['138', 'Route 138'] },
    { code: '112', type: 'Route', label: 'Route 112', synonyms: ['112', 'Route 112'] },
    { code: '117', type: 'Route', label: 'Route 117', synonyms: ['117', 'Route 117'] },
    { code: '125', type: 'Route', label: 'Route 125', synonyms: ['125', 'Route 125'] },
    { code: '148', type: 'Route', label: 'Route 148', synonyms: ['148', 'Route 148'] },
    { code: '175', type: 'Route', label: 'Route 175', synonyms: ['175', 'Route 175'] },
    { code: '185', type: 'Route', label: 'Route 185', synonyms: ['185', 'Route 185'] }
  ],
  'US-MI': [
    { code: 'I-75', type: 'Interstate', label: 'I-75', synonyms: ['I-75', 'Interstate 75', '75'] },
    { code: 'I-94', type: 'Interstate', label: 'I-94', synonyms: ['I-94', 'Interstate 94', '94'] },
    { code: 'I-96', type: 'Interstate', label: 'I-96', synonyms: ['I-96', 'Interstate 96', '96'] },
    { code: 'I-69', type: 'Interstate', label: 'I-69', synonyms: ['I-69', 'Interstate 69', '69'] },
    { code: 'I-194', type: 'Interstate', label: 'I-194', synonyms: ['I-194'] },
    { code: 'I-196', type: 'Interstate', label: 'I-196', synonyms: ['I-196'] },
    { code: 'I-275', type: 'Interstate', label: 'I-275', synonyms: ['I-275'] },
    { code: 'I-296', type: 'Interstate', label: 'I-296', synonyms: ['I-296'] },
    { code: 'I-375', type: 'Interstate', label: 'I-375', synonyms: ['I-375'] },
    { code: 'I-475', type: 'Interstate', label: 'I-475', synonyms: ['I-475'] },
    { code: 'I-496', type: 'Interstate', label: 'I-496', synonyms: ['I-496'] },
    { code: 'I-675', type: 'Interstate', label: 'I-675', synonyms: ['I-675'] },
    { code: 'I-696', type: 'Interstate', label: 'I-696', synonyms: ['I-696'] },
    { code: 'US-2', type: 'US', label: 'US-2', synonyms: ['US-2', 'US 2', '2'] },
    { code: 'US-10', type: 'US', label: 'US-10', synonyms: ['US-10', 'US 10', '10'] },
    { code: 'US-12', type: 'US', label: 'US-12', synonyms: ['US-12', 'US 12', '12'] },
    { code: 'US-23', type: 'US', label: 'US-23', synonyms: ['US-23', 'US 23', '23'] },
    { code: 'US-24', type: 'US', label: 'US-24', synonyms: ['US-24', 'US 24', '24'] },
    { code: 'US-31', type: 'US', label: 'US-31', synonyms: ['US-31', 'US 31', '31'] },
    { code: 'US-41', type: 'US', label: 'US-41', synonyms: ['US-41', 'US 41', '41'] },
    { code: 'US-127', type: 'US', label: 'US-127', synonyms: ['US-127', 'US 127', '127'] },
    { code: 'US-131', type: 'US', label: 'US-131', synonyms: ['US-131', 'US 131', '131'] },
    { code: 'US-223', type: 'US', label: 'US-223', synonyms: ['US-223', 'US 223', '223'] },
    { code: 'M-1', type: 'State', label: 'M-1', synonyms: ['M-1', 'M 1', '1'] },
    { code: 'M-3', type: 'State', label: 'M-3', synonyms: ['M-3', 'M 3', '3'] },
    { code: 'M-5', type: 'State', label: 'M-5', synonyms: ['M-5', 'M 5', '5'] },
    { code: 'M-6', type: 'State', label: 'M-6', synonyms: ['M-6', 'M 6', '6'] },
    { code: 'M-10', type: 'State', label: 'M-10', synonyms: ['M-10', 'M 10', '10'] },
    { code: 'M-14', type: 'State', label: 'M-14', synonyms: ['M-14', 'M 14', '14'] },
    { code: 'M-15', type: 'State', label: 'M-15', synonyms: ['M-15', 'M 15', '15'] },
    { code: 'M-18', type: 'State', label: 'M-18', synonyms: ['M-18', 'M 18', '18'] },
    { code: 'M-20', type: 'State', label: 'M-20', synonyms: ['M-20', 'M 20', '20'] },
    { code: 'M-24', type: 'State', label: 'M-24', synonyms: ['M-24', 'M 24', '24'] },
    { code: 'M-28', type: 'State', label: 'M-28', synonyms: ['M-28', 'M 28', '28'] },
    { code: 'M-32', type: 'State', label: 'M-32', synonyms: ['M-32', 'M 32', '32'] },
    { code: 'M-37', type: 'State', label: 'M-37', synonyms: ['M-37', 'M 37', '37'] },
    { code: 'M-39', type: 'State', label: 'M-39', synonyms: ['M-39', 'M 39', '39'] },
    { code: 'M-43', type: 'State', label: 'M-43', synonyms: ['M-43', 'M 43', '43'] },
    { code: 'M-46', type: 'State', label: 'M-46', synonyms: ['M-46', 'M 46', '46'] },
    { code: 'M-50', type: 'State', label: 'M-50', synonyms: ['M-50', 'M 50', '50'] },
    { code: 'M-53', type: 'State', label: 'M-53', synonyms: ['M-53', 'M 53', '53'] },
    { code: 'M-55', type: 'State', label: 'M-55', synonyms: ['M-55', 'M 55', '55'] },
    { code: 'M-59', type: 'State', label: 'M-59', synonyms: ['M-59', 'M 59', '59'] },
    { code: 'M-60', type: 'State', label: 'M-60', synonyms: ['M-60', 'M 60', '60'] },
    { code: 'M-66', type: 'State', label: 'M-66', synonyms: ['M-66', 'M 66', '66'] },
    { code: 'M-72', type: 'State', label: 'M-72', synonyms: ['M-72', 'M 72', '72'] },
    { code: 'M-82', type: 'State', label: 'M-82', synonyms: ['M-82', 'M 82', '82'] },
    { code: 'M-96', type: 'State', label: 'M-96', synonyms: ['M-96', 'M 96', '96'] },
    { code: 'M-97', type: 'State', label: 'M-97', synonyms: ['M-97', 'M 97', '97'] },
    { code: 'M-115', type: 'State', label: 'M-115', synonyms: ['M-115', 'M 115', '115'] },
    { code: 'M-116', type: 'State', label: 'M-116', synonyms: ['M-116', 'M 116', '116'] },
    { code: 'M-119', type: 'State', label: 'M-119', synonyms: ['M-119', 'M 119', '119'] },
    { code: 'M-123', type: 'State', label: 'M-123', synonyms: ['M-123', 'M 123', '123'] }
  ]
};
